AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket for storing media files

Resources:
  MediaProcessorApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'POST,GET'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      BinaryMediaTypes:
        - '*/*'
      OpenApiVersion: '3.0.1'
      DefinitionBody:
        openapi: '3.0.1'
        paths:
          /image/{proxy+}:
            get:
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ImageProcessorFunction.Arn}/invocations
                contentHandling: CONVERT_TO_BINARY
                passthroughBehavior: when_no_match
                timeoutInMillis: 29000
          /doc/{proxy+}:
            post:
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DocumentProcessorFunction.Arn}/invocations
                contentHandling: CONVERT_TO_BINARY
                passthroughBehavior: when_no_match
                timeoutInMillis: 29000
          /task/{task_id}:
            get:
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DocumentProcessorFunction.Arn}/invocations
                contentHandling: CONVERT_TO_BINARY
                passthroughBehavior: when_no_match
                timeoutInMillis: 29000
          /video/{proxy+}:
            get:
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${VideoProcessorFunction.Arn}/invocations
                contentHandling: CONVERT_TO_BINARY
                passthroughBehavior: when_no_match
                timeoutInMillis: 29000

  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image-processor/
      Runtime: python3.9
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref BucketName
      Handler: handler.handler
      Timeout: 30
      MemorySize: 512
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName
      Events:
        GetImageAPI:
          Type: Api
          Properties:
            Path: /image/{proxy}
            Method: get
            RestApiId: !Ref MediaProcessorApi

  VideoProcessorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: latest
      DockerContext: video-processor
      Dockerfile: Dockerfile
    Properties:
      PackageType: Image
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref BucketName
      Timeout: 30
      MemorySize: 2048
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName
      Events:
        GetVideoAPI:
          Type: Api
          Properties:
            Path: /video/{proxy}
            Method: get
            RestApiId: !Ref MediaProcessorApi

  DocumentProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DocumentProcessorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub arn:${AWS::Partition}:s3:::${BucketName}/*
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt TasksTable.Arn
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - lambda:InvokeAsync
                Resource: '*'

  DocumentProcessorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: latest
      DockerContext: document-processor
      Dockerfile: Dockerfile
    Properties:
      PackageType: Image
      Role: !GetAtt DocumentProcessorRole.Arn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref BucketName
          DDB_TABLE_NAME: !Ref TasksTable
      Timeout: 60
      MemorySize: 1024
      Events:
        ProcessAPI:
          Type: Api
          Properties:
            Path: /doc/{proxy+}
            Method: post
            RestApiId: !Ref MediaProcessorApi
        GetTaskAPI:
          Type: Api
          Properties:
            Path: /task/{task_id}
            Method: get
            RestApiId: !Ref MediaProcessorApi

  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-tasks
      AttributeDefinitions:
        - AttributeName: TaskId
          AttributeType: S
        - AttributeName: TaskType
          AttributeType: S
      KeySchema:
        - AttributeName: TaskId
          KeyType: HASH
        - AttributeName: TaskType
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${MediaProcessorApi}.execute-api.${AWS::Region}.amazonaws.com.cn/prod"
  ImageEndpoint:
    Description: Image processing endpoint
    Value: !Sub "https://${MediaProcessorApi}.execute-api.${AWS::Region}.amazonaws.com.cn/prod/image/{key}?operations=resize,w_1000/watermark,text_54mI5p2D5omA5pyJ/format,jpg"
  DocumentEndpoint:
    Description: Document processing endpoint
    Value: !Sub "https://${MediaProcessorApi}.execute-api.${AWS::Region}.amazonaws.com.cn/prod/doc/{object_key}?operations=convert,target_png,source_docx"
  TaskEndpoint:
    Description: Task status endpoint
    Value: !Sub "https://${MediaProcessorApi}.execute-api.${AWS::Region}.amazonaws.com.cn/prod/task/{task_id}"
  VideoEndpoint:
    Description: Video processing endpoint
    Value: !Sub "https://${MediaProcessorApi}.execute-api.${AWS::Region}.amazonaws.com.cn/prod/video/{key}?operations=snapshot,t_5000,f_jpg,w_1280,h_720"
  TasksTableName:
    Description: Name of the DynamoDB table for task tracking
    Value: !Ref TasksTable
